-- BORRADO DE OBJETOS

-- Tablas de Morosidad
DROP TABLE AUDITORIA_PAGOS CASCADE CONSTRAINTS;
DROP TABLE AUDITORIA_MOROSIDADES CASCADE CONSTRAINTS;
DROP TABLE DETALLE_MOROSIDAD CASCADE CONSTRAINTS;

-- Paquetes PL/SQL
DROP PACKAGE PKG_MOROSIDADES;
DROP PACKAGE PKG_RESIDENTES;

-- Triggers
DROP TRIGGER TRG_VALIDAR_AUDITORIA_PAGO;
DROP TRIGGER TRG_AUDITORIA_MOROSIDAD;

-- Tablas principales
DROP TABLE PAGO_GASTO_COMUN CASCADE CONSTRAINTS;
DROP TABLE GASTO_COMUN_PAGO_CERO CASCADE CONSTRAINTS;
DROP TABLE GASTO_COMUN CASCADE CONSTRAINTS;
DROP TABLE RESPONSABLE_PAGO_GASTO_COMUN CASCADE CONSTRAINTS;
DROP TABLE TIPO_PERSONA CASCADE CONSTRAINTS;
DROP TABLE MULTA_ATRASO CASCADE CONSTRAINTS;
DROP TABLE FORMA_PAGO CASCADE CONSTRAINTS;
DROP TABLE ESTADO_PERIODO CASCADE CONSTRAINTS;
DROP TABLE ESTADO_PAGO CASCADE CONSTRAINTS;
DROP TABLE PERIODO_COBRO_GASTO_COMUN CASCADE CONSTRAINTS;
DROP TABLE DEPARTAMENTO CASCADE CONSTRAINTS;
DROP TABLE EDIFICIO CASCADE CONSTRAINTS;
DROP TABLE ADMINISTRADOR CASCADE CONSTRAINTS;
DROP TABLE COMUNA CASCADE CONSTRAINTS;
DROP SEQUENCE seq_com;
